version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_clientes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
